### ISSUE TITLE
AutoStart issue

### ISSUE THREAD

**Issue by dharm910** [simonclausen/dnscrypt-autoinstall#72] opened 2015-12-05 15:20 UTC
The script does not work with reboot of Linux . I have to always run it manually after the restart.
This is the log which I gets once I run the script manually.
Starting dnscrypt-proxy
chattr: Operation not supported while reading flags on /etc/resolv.conf
chattr: Operation not supported while reading flags on /etc/resolv.conf
Reconfiguration done. Quitting

**Comment by AladW** [comment] 2015-12-06 17:37
What distribution?

**Comment by dharm910** [comment] 2015-12-08 21:17
I am using Linux Mint 17.2 Rafaela however , today after reinstallation it is now auto starting after reboot not sure what it was not working before.
Did you tried uninstallation of the script ?

**Comment by AladW** [comment] 2016-02-12 08:34
Post ```ls -l /etc/resolv.conf```

**Comment by simonclausen** [comment] 2016-03-11 08:39
@dharm910, please get back with more info on this, if still relevant.

Keeping open because possible relation to #71

**Comment by williclarkam** [comment] 2016-03-12 20:22
I think this issue doesn't happen on Debian 8 (Jessie) because every time that I reboot the server, I issue the command `sudo tail -n 200 /var/log/syslog` and the output shows that dnscrypt-proxy has started. but still I maybe wrong, still new to Linux ;)

**Comment by dharm910** [comment] 2016-03-18 21:15
I am not facing any issue now as after a reinstallation it's working fine now

**Comment by AladW** [comment] 2016-06-28 08:55
Without more information, I'm going to classify this as a dupe of #79

**Closed by AladW** 2016-06-28 08:55 UTC
Labels: duplicate
