### ISSUE TITLE
DNSCrypt not starting after reboot in Ubuntu 15.10

### ISSUE THREAD

**Issue by wrsg** [simonclausen/dnscrypt-autoinstall#71] opened 2015-11-15 18:06 UTC
Using Ubuntu 15.10
The install process seems to work fine but after reboot, it is no longer active.

**Comment by AladW** [comment] 2015-12-06 17:38
Could you get some logs? Possibly related: #72

**Comment by simonclausen** [comment] 2016-03-11 08:40
@wrsg, please get back to us with some more info

**Comment by wrsg** [comment] 2016-03-16 19:26
Hi @simonclausen, let me know what you need, sorry about the delay in getting back to you

**Comment by wrsg** [comment] 2016-05-27 16:27
bump?

**Comment by simonclausen** [comment] 2016-06-02 19:28
Any log file indicating what is going on or not going on, content of /etc/resolv.conf, output of "netstat -nap | grep :53"

**Comment by AladW** [comment] 2016-06-28 08:54
Without more information, I'm going to classify this as a dupe of #79

**Closed by AladW** 2016-06-28 08:54 UTC
Labels: needsinfo

**Comment by wrsg** [comment] 2016-07-05 16:13
Sorry for the late reply on the error logs
[dncrypt proxy anton errors.txt](https://github.com/simonclausen/dnscrypt-autoinstall/files/348169/dncrypt.proxy.anton.errors.txt)
[dnscrypterror.txt](https://github.com/simonclausen/dnscrypt-autoinstall/files/348170/dnscrypterror.txt)
[dnscrypterror3.txt](https://github.com/simonclausen/dnscrypt-autoinstall/files/348171/dnscrypterror3.txt)

**Comment by AladW** [comment] 2016-07-05 16:25
You should report a bug to the author of the PPA, it's separate from this project.
